name: CI/CD Frontend

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate .env file from GitHub secrets
        run: |
          echo "NGINX_SERVER_NAME=${{ secrets.NGINX_SERVER_NAME }}" >> .env
          echo "VITE_COREURL=${{ secrets.VITE_COREURL }}" >> .env
          echo "VITE_MONGOURL=${{ secrets.VITE_MONGOURL }}" >> .env
          echo "VITE_URL=${{ secrets.VITE_URL }}" >> .env
          
      - name: Build and Push Docker Image
        run: |
          docker build -t igrowker/i004-mindup-front:${{ github.sha }} .
          docker tag igrowker/i004-mindup-front:${{ github.sha }} igrowker/i004-mindup-front:latest
          docker push igrowker/i004-mindup-front:${{ github.sha }}
          docker push igrowker/i004-mindup-front:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: [self-hosted, frontend-deploy]
    
    steps:
      - name: Deploy Frontend to EC2
        run: |
            cd /home/admin/frontend &&
            sudo docker pull igrowker/i004-mindup-front:${{ github.sha }} &&
            sudo docker stop mindup-front || true &&
            sudo docker rm mindup-front || true &&
            sudo docker run -d \
              --name mindup-front \
              -p 80:80 \
              -e VITE_COREURL=${{ secrets.VITE_COREURL }} \
              -e VITE_MONGOURL=${{ secrets.VITE_MONGOURL }} \
              -e VITE_URL=${{ secrets.VITE_URL }} \
              -e NGINX_SERVER_NAME=${{ secrets.NGINX_SERVER_NAME }} \
              igrowker/i004-mindup-front:${{ github.sha }}
